version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version

      # Logging into the ECR with correct region
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 954976297502.dkr.ecr.ap-northeast-1.amazonaws.com
      # Setting repository URI and image tag
      - REPOSITORY_URI=954976297502.dkr.ecr.ap-northeast-1.amazonaws.com/spring-demo-ecr
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Jar file...
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing to Amazon ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - DOCKER_CONTAINER_NAME=spring-demo-ecr
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo printing imagedefinitions.json...
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

    - target/springboot-aws-deploy-service.jar

